import asyncio
from typing import AsyncIterator, Optional

from ai_core.base import (
    BaseLLMProvider,
    ChatRole,
    GenerationResult,
    MessageInput,
    ModelConfig,
    StreamChunk,
    TokenUsage,
)


class MockProvider(BaseLLMProvider):
    """
    Mock AI Provider generating simulated responses for offline development and unit tests.
    """

    async def generate(
        self,
        messages: MessageInput,
        config: Optional[ModelConfig] = None,
    ) -> GenerationResult:
        normalized = self._normalize_messages(messages)
        last_message = normalized[-1].content if normalized else "Hello"
        cfg = config or ModelConfig(model_name="mock-provider")

        content = f"Mock response for prompt: '{last_message}'. (Configure GEMINI_API_KEY or OPENAI_API_KEY for live completions)."
        return GenerationResult(
            content=content,
            role=ChatRole.ASSISTANT,
            model_name=cfg.model_name,
            usage=TokenUsage(
                prompt_tokens=len(last_message.split()),
                completion_tokens=len(content.split()),
                total_tokens=len(last_message.split()) + len(content.split()),
            ),
        )

    async def stream(
        self,
        messages: MessageInput,
        config: Optional[ModelConfig] = None,
    ) -> AsyncIterator[StreamChunk]:
        normalized = self._normalize_messages(messages)
        last_message = normalized[-1].content if normalized else "Hello"

        paragraphs = [
            f"**GraphMind Simulated Response** for: *'{last_message}'*\n\n",
            "This is a simulated token stream generated by `MockProvider` because no active API key was detected.\n\n",
            "• **Provider Abstraction**: Working as designed via `packages/ai-core`.\n",
            "• **Message Input**: Multi-turn `ChatMessage` structure normalized successfully.\n\n",
            "Set `GEMINI_API_KEY` in your `.env` file to stream live Google Gemini completions!",
        ]
        for paragraph in paragraphs:
            for word in paragraph.split(" "):
                yield StreamChunk(content=word + " ")
                await asyncio.sleep(0.03)
