import asyncio
from typing import AsyncIterator, Optional

from ai_core.base import (
    BaseLLMProvider,
    ChatRole,
    GenerationResult,
    MessageInput,
    ModelConfig,
    StreamChunk,
    TokenUsage,
)


class MockProvider(BaseLLMProvider):
    """
    Mock AI Provider generating simulated responses for offline development,
    deterministic automated tests, and error simulation.
    """

    async def generate(
        self,
        messages: MessageInput,
        config: Optional[ModelConfig] = None,
    ) -> GenerationResult:
        cfg = config or ModelConfig(model_name="mock-provider")
        if cfg.metadata.get("simulate_error"):
            raise RuntimeError("Simulated MockProvider generation error.")

        normalized = self._normalize_messages(messages)
        last_message = normalized[-1].content if normalized else "Hello"

        content = (
            f"**GraphMind Mock Completion**\n\n"
            f"Response for prompt: *'{last_message}'* (Turns: {len(normalized)})\n\n"
            f"```python\n"
            f"# Sample code snippet generated by MockProvider\n"
            f"def solve_problem() -> str:\n"
            f"    return 'GraphMind knowledge graph initialized'\n"
            f"```"
        )
        return GenerationResult(
            content=content,
            role=ChatRole.ASSISTANT,
            model_name=cfg.model_name,
            usage=TokenUsage(
                prompt_tokens=len(last_message.split()),
                completion_tokens=len(content.split()),
                total_tokens=len(last_message.split()) + len(content.split()),
            ),
        )

    async def stream(
        self,
        messages: MessageInput,
        config: Optional[ModelConfig] = None,
    ) -> AsyncIterator[StreamChunk]:
        cfg = config or ModelConfig(model_name="mock-provider")
        if cfg.metadata.get("simulate_error"):
            raise RuntimeError("Simulated MockProvider stream error.")

        delay = float(cfg.metadata.get("stream_delay", 0.02))
        normalized = self._normalize_messages(messages)
        last_message = normalized[-1].content if normalized else "Hello"

        paragraphs = [
            f"**GraphMind Simulated Response** for: *'{last_message}'*\n\n",
            "This is a high-speed token stream generated by `MockProvider`.\n\n",
            "### Architecture Highlights\n",
            "• **Provider-Agnostic**: Decoupled via `packages/ai-core` interfaces.\n",
            "• **Multi-Turn Lineage**: Received conversation depth of "
            f"`{len(normalized)}` message(s).\n\n",
            "```python\n",
            "# Example architecture code block\n",
            "async def handle_stream():\n",
            "    async for chunk in provider.stream(prompt):\n",
            "        yield chunk.content\n",
            "```\n\n",
            "Ready for Phase 1 streaming validation!",
        ]

        for paragraph in paragraphs:
            for word in paragraph.split(" "):
                yield StreamChunk(content=word + " ")
                if delay > 0:
                    await asyncio.sleep(delay)
